# Generated by Django 2.2.10 on 2021-05-24 12:54

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_codigo', models.CharField(max_length=255, verbose_name='cliente_codigo')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=255, verbose_name='apellido')),
                ('clasificacion_global_ano_act', models.TextField(blank=True, verbose_name='clasificacion_global_ano_act')),
                ('facturacion_ano_ant', models.TextField(blank=True, verbose_name='facturacion_ano_ant')),
                ('clasificacion_potencial', models.TextField(blank=True, verbose_name='clasificacion_potencial')),
                ('acuerdo', models.TextField(blank=True, verbose_name='acuerdo')),
                ('nif', models.TextField(blank=True, verbose_name='nif')),
                ('bloqueado', models.BooleanField(default=True, verbose_name='bloqueado')),
                ('grupo_compra', models.TextField(blank=True, verbose_name='grupo_compra')),
                ('clasificacion_global_ano_ant', models.TextField(blank=True, verbose_name='clasificacion_global_ano_ant')),
                ('facturacion_ano_act', models.TextField(blank=True, verbose_name='facturacion_ano_act')),
                ('acepta_el_contrato', models.BooleanField(default=True, verbose_name='acepta_el_contrato')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='Forma_pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('seleccionable', models.IntegerField(blank=True, null=True, verbose_name='seleccionable')),
                ('necesita', models.IntegerField(blank=True, null=True, verbose_name='necesita')),
                ('iban', models.CharField(max_length=255, verbose_name='iban')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='Gama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Changed')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Changed')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_unidad', models.TextField(blank=True, verbose_name='tipo_unidad')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('moneda', models.TextField(blank=True, verbose_name='moneda')),
                ('activo_pedido', models.BooleanField(default=False, verbose_name='activo_pedido')),
                ('activo_devolucion', models.BooleanField(default=False, verbose_name='activo_devolucion')),
                ('es_medicamento', models.BooleanField(default=False, verbose_name='es_medicamento')),
                ('cod_nacional', models.TextField(blank=True, verbose_name='cod_nacional')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Changed')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('gama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Gama')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Negocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('orden_listado', models.IntegerField(blank=True, null=True, verbose_name='orden_listado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Changed')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_retos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('n_producto', models.IntegerField(blank=True, null=True, verbose_name='n_producto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Changed')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='Productos_retos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Productos')),
                ('tipo_retos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Tipo_retos')),
            ],
        ),
        migrations.CreateModel(
            name='Productos_regalo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('Tipo_retos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Tipo_retos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Productos')),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='tipo_articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Tipo_producto'),
        ),
        migrations.AddField(
            model_name='gama',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Marca'),
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=255, verbose_name='apellido')),
                ('telefono', phone_field.models.PhoneField(blank=True, help_text='Telefono de Contacto', max_length=31)),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='fecha_nacimiento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Changed')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_retos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('firma', models.BooleanField(default=True, verbose_name='Firma')),
                ('fecha_ini', models.DateField(null=True, verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(null=True, verbose_name='Fecha Fin')),
                ('max_venta', models.BigIntegerField(verbose_name='Maximo de Ventas')),
                ('n_ventas_activas', models.BigIntegerField(verbose_name='Numero de ventas activas')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Changed')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Cliente')),
                ('tipos_retos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Tipo_retos')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='forma_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Forma_pago'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_Negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Tipo_Negocio'),
        ),
    ]
