# Generated by Django 2.2.10 on 2021-05-25 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cli_retos_art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_ticket', models.CharField(max_length=255, verbose_name='nombre')),
                ('images', models.ImageField(upload_to='Nº Ticket', verbose_name='Imágen')),
                ('validar_foto', models.BooleanField(default=False, verbose_name='Validar')),
                ('clave_reto_farmacia', models.CharField(max_length=255, verbose_name='Clave')),
                ('fecha_alta', models.DateField(null=True, verbose_name='Fecha Alta')),
                ('Productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Productos')),
                ('cliente_reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Cliente_retos')),
                ('productos_regalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Productos_regalo')),
            ],
        ),
    ]
