# Generated by Django 2.2.10 on 2021-06-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0002_cli_retos_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli_retos_art',
            name='images',
            field=models.ImageField(upload_to='images', verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='cli_retos_art',
            name='n_ticket',
            field=models.CharField(max_length=255, verbose_name='Nº Ticket'),
        ),
    ]
