# Generated by Django 2.2.10 on 2021-06-03 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0003_auto_20210601_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli_retos_art',
            name='fecha_alta',
            field=models.DateField(default=datetime.date(2021, 6, 3), verbose_name='Fecha Alta'),
        ),
    ]
