# Generated by Django 2.2.10 on 2021-06-04 09:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0004_auto_20210603_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli_retos_art',
            name='fecha_alta',
            field=models.DateField(default=datetime.date(2021, 6, 4), verbose_name='Fecha Alta'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retos.Cliente'),
        ),
    ]
